export default () => {
  return {
    1: "Mainly clear",
    0: "Clear sky",
    2: "Partly cloudy",
    3: "Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "Light drizzle",
    53: "Moderate drizzle",
    55: "Dense intensity",
    56: "Light Frosty drizzling rain",
    57: "Frosty drizzling rain dense intensity",
    61: "Light rain",
    63: "Moderate rain",
    65: "Heavy rain",
    66: "Light icy rain",
    67: "Icy rain of strong intensity",
    71: "Light snowfall",
    73: "Moderate snowfall",
    75: "Heavy snowfall",
    77: "Snow grains",
    80: "Light rain showers",
    81: "Moderate rain showers",
    82: "Heavy rain showers",
    85: "Light snow showers",
    86: "Heavy snow showers ",
    95: "Moderate thunderstorm",
    96: "Thunderstorm with small hail",
    99: "Thunderstorm with heavy hail",
  }
};
